### PR TITLE
Update project to use Android Gradle plugin v3.x

### LINKED ISSUE #54: issue when building project
I am getting the following when trying to build the project: 

Error:Cannot choose between the following configurations of project :barricade:
  - debugApiElements
  - debugRuntimeElements
  - releaseApiElements
  - releaseRuntimeElements
All of them match the consumer attributes:
  - Configuration 'debugApiElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
  - Configuration 'debugRuntimeElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.
  - Configuration 'releaseApiElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
  - Configuration 'releaseRuntimeElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.

### PR DESCRIPTION
**Pull request by mustafa01ali**
- Updated the project to use the latest Gradle plugin 
- Updated all the other dependencies
- Updated Travis config
- The response builder in OkHttp 3.8 has made the response `message` mandatory which Barricade was not passing, causing IllegalStateExceptions. I've fixed that issue by hardcoding a static message for now. In the future, we could make even the message configurable like we do for status codes.

Fixes #54

### CODE REVIEW

**Comment by mustafa01ali** [comment]
Alright, it's late now and Travis refuses to behave. Will look into the build failure tomorrow.

**Comment by Emeritus-DarranKelinske** [comment]
thank you!

**Comment by Emeritus-DarranKelinske** [comment]
Does this help? https://github.com/OneBusAway/onebusaway-android/commit/fa98297ecf9823e2cdb989a87900cadaa770e130

**Comment by Emeritus-DarranKelinske** [comment]
This might be better: https://stackoverflow.com/a/28751112/3268303

**Comment by dazza5000** [comment]
@mustafa01ali i miss you

**Comment by mustafa01ali** [comment]
Hey guys, got busy with work. Will try and work on this tonight.

**Comment by mustafa01ali** [comment]
I spent several hours trying to fix the Travis emulator issue with no luck. A similar [issue](https://github.com/travis-ci/travis-ci/issues/7425) was reported to Travis back in March but they haven't bothered to look into it till now.

I've disabled running instrumentation tests for now to unblock this and created #56 to find a solution for the CI issue.

Note: Since these changes do not change the library API or behaviour, we will not be publishing an update to Bintray.

**Pull request merged**
